### ISSUE TITLE
How to test startFlexibleUpdate()

### ISSUE THREAD

**Issue by sagits** [robingenz/capacitor-app-update#10]
Hi, very nice plugin, thanks for helping the community. 

I'm receiving code 3 (UPDATE_NOT_AVAILABLE ) on startFlexibleUpdate() in an Android Device while testing. For testing purposes I have downgraded the debug version to 99521, while the production version in app store is v 99522. I received the error and I saw no modal, I believe this happened because the .keystore is not the same or some other form of debug x production issue. Am I right? Is there a way to test it without going into production? Thanks in advance.

![image](https://user-images.githubusercontent.com/6174566/109857788-d1d04700-7c39-11eb-9489-e2c36ca788f0.png)

**Comment by robingenz** [comment]
Hi, thank you!
The Android Developers documentation describes how to test in-app updates with internal app-sharing: https://developer.android.com/guide/playcore/in-app-updates#internal-app-sharing
Furthermore, there is a good post on Stackoverflow: https://stackoverflow.com/questions/56087064/how-can-i-test-in-app-updates-in-android
Unfortunately, I have not yet been able to gain much experience with the plugin myself, as I am still actively developing it.
I will add some information about this topic to the README in the future.

Let me know if there are any problems.

**Comment by sagits** [comment]
Thanks for the info.

I tried every available approach and still no luck. I tried Internal app-sharing, the internal test track, and even the prod track.

I'm not sure which code I'm receiving because I can't debug on prod, but I believe that it's still the error code 3. Strangely, it detects that the currentVersion is lower than the availableVersion, but doesn't show the update modal (I put a toast on the internal track to check that).

I believe it has to do with being an internal tester (I even tried with a different account on the same device and nothing). I'll try on another device and edit this post to help other users when I find the solution.

**Comment by robingenz** [comment]
I am currently preparing my app for testing. As soon as I have done my tests, I will give you feedback and hopefully be able to help you further.

**Comment by Anket-21** [comment]
Is it done working ?

**Comment by robingenz** [comment]
Checking the version details on Android and iOS has been successfully tested with Capacitor 3.
Unfortunately, I haven't had the time to test the Android in-app updates yet. However, there has been a lot of positive feedback from the community since the Capacitor 3 update. For that reason, I believe that it works fine.
I am happy to receive any further feedback!

**Comment by robingenz** [comment]
A user has tested the plugin and told me that everything works fine (see [here](https://github.com/robingenz/capacitor-app-update/issues/20#issuecomment-903675081)). 
I have just released version 1.0.0:
```
npm i @robingenz/capacitor-app-update@1.0.0
```
For this reason, I am closing this Issue.
