### ISSUE TITLE
Support for country URL param

### ISSUE THREAD

**Issue by hemangsk** [robingenz/capacitor-app-update#12]
Hi, thanks a lot for making this cool plugin!

I noticed that in scenarios when the app is not in available in a country, the lookup API URL doesn't work in that case and returns an empty JSON, which makes sense. In order to get a response in this case, the plugin can allow users to chose to pass an argument to an optional ```country``` parameter in getAppUpdateInfo and openAppStore methods. I'm happy to send in a PR if this addition makes sense.

**Comment by robingenz** [comment]
Hi, good point! This would definitely make sense. However, I would like to fully test the plugin first and update to Capacitor 3. 
After that I would be very happy if we could add this feature to the plugin.

**Comment by hemangsk** [comment]
Great! thanks :)

**Comment by robingenz** [comment]
Hi @hemangsk, 
if you still want to implement this feature, feel free to send me a PR. The update to Capacitor 3 has been successfully completed.
I would suggest the following interface:

**Comment by hemangsk** [comment]
Will do! and Thank you for providing specs for the interface

**Comment by robingenz** [comment]
Great! Thank you! Ping me if you need any help.
(I have just updated the interface again.)

**Comment by robingenz** [comment]
Resolved by #26
