### ISSUE TITLE
type: question

### ISSUE THREAD

**Issue by KrishPro** [robingenz/capacitor-app-update#17]
### Wanted to ask that after performing immediate update Why you're not resolving the PluginCall...And...In the function ready for update  at line 189 

Isn't it problematic. You're stating Update Not available if update is available.... 

```
if (this.appUpdateInfo.updateAvailability() == UpdateAvailability.UPDATE_AVAILABLE) {
            ret.put("code", this.UPDATE_NOT_AVAILABLE);
            call.resolve(ret);
            return false;
}
```

**Comment by robingenz** [comment]
The plugin call is resolved in `handleOnActivityResult`.

Line 189: Good catch! I will fix this.
Unfortunately I still haven't had time to test the plugin.
