### ISSUE TITLE
bug: Updates dont work

### ISSUE THREAD

**Issue by webzlodimir** [robingenz/capacitor-app-update#18]
**Describe the bug**
Try to use plugin

**To Reproduce**
All steps by readme

```
import { AppUpdate } from "@robingenz/capacitor-app-update";
const performImmediateUpdate = async () => {
  const result = await AppUpdate.getAppUpdateInfo();
  alert(JSON.stringify(result, null, 4));
  const anotherResutl = await AppUpdate.performImmediateUpdate();
  alert(JSON.stringify(anotherResutl, null, 4));
};
```

**Expected behavior**
Window with update

**Screenshots**
![photo_2021-07-26_13-44-29](https://user-images.githubusercontent.com/31979423/126982024-14989b47-6ab8-4bfa-a896-6e0ef2bcdbd8.jpg)

**Smartphone (please complete the following information):**

- Android Emulator Pixel 4
- Android 11 API 30

**Additional context**

- Plugin version: 1.0.0-alpha.3
- Capacitor version: 3
- androidPlayCore = '1.10.0'

**Comment by robingenz** [comment]
Thank you for the request.
Did you follow [this guide](https://developer.android.com/guide/playcore/in-app-updates/test), especially the [troubleshoot part](https://developer.android.com/guide/playcore/in-app-updates/test#troubleshoot)?
There are many things you can do wrong. Therefore, please check again if you have followed the instructions exactly.
Also check out this: https://stackoverflow.com/a/68379437

**Comment by webzlodimir** [comment]
Thanks for the help. It was my mistake, I confused internal testing and internal sharing ¯\_(ツ)_/¯
