### ISSUE TITLE
bug: error while trying to get appUpdateInfo

### ISSUE THREAD

**Issue by sanderschnydrig** [robingenz/capacitor-app-update#19]
**Capacitor Doctor**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/ios: 3.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

I was trying this plugin (^1.0.0-alpha.3) with the latest version of Capacitor v3 and when trying to call the AppUpdate.getAppUpdateInfo() I get the following error message:

`
{message: "Required app information could not be fetched", errorMessage: "Required app information could not be fetched"}
`

followed by
`
Error: Uncaught (in promise): Error: Required app information could not be fetched i@capacitor://localhost/main-es2015.8ff1e5aae7b0a67b0188.js:1:670532 
`

**Expected behavior**
I expect to get information about app/play store updates and the current version of the application

**Smartphone (please complete the following information):**

iPhone 12 simulator

**Comment by robingenz** [comment]
Thank you for your request.
Does the error occur on Android or iOS?

**Comment by sanderschnydrig** [comment]
@robingenz thanks for the quick response! I'm getting the error on iOS only. On Android I get current version: 23, available version: 0.

**Comment by robingenz** [comment]
Would you like to give me your CFBundleIdentifier?
If you do not want this, please go to the following URL and paste the output here: 
```
https://itunes.apple.com/lookup?bundleId=YOUR_CF_BUNDLE_IDENTIFIER
```
Please replace `YOUR_CF_BUNDLE_IDENTIFIER` with your CFBundleIdentifier.

By the way: You should make sure that the device has an internet connection when you call `getAppUpdateInfo`.

**Regarding Android**: You should be able to test this plugin using internal app sharing. If there are any problems, check out [this comment](https://github.com/robingenz/capacitor-app-update/issues/18#issuecomment-886706841). If this does not help you, please create an additional issue.

**Comment by sanderschnydrig** [comment]
The output im getting for 

```
https://itunes.apple.com/lookup?bundleId=ch.rro.capacitor
```

is

```
{
 "resultCount":0,
 "results": []
}
```

I always have an internet connection when trying the above code and tried running the app from XCode as well as internal Testing on Testflight, but I haven't been able to debug the app if its coming from a Testflight installation.

**Comment by robingenz** [comment]
The response should include at least one result ([example](https://itunes.apple.com/lookup?bundleId=de.dhbw.vs.standortapp)).
Is it possible that your iOS app is only available in certain countries?
In fact, it sounds like the following problem: https://stackoverflow.com/questions/14640834/itunes-lookupbundleid-method-is-not-working-for-my-app
In that case, implementing the following feature would solve your problem: #12

**Comment by sanderschnydrig** [comment]
Hi robingenz
I've stumbled across this issue before and tried to add the country code like in the suggestion with the same empty result:

https://itunes.apple.com/ch/lookup?bundleId=ch.rro.capacitor

According to [this newer issue](https://stackoverflow.com/questions/8839328/itunes-api-lookup-by-bundle-id) Apple removed the way they handle country codes so I also tried this URL with the same result:
https://itunes.apple.com/lookup?bundleId=ch.rro.capacitor&country=ch

The app should be available in all countries (as stated on the app store connect website). However it is still in Testflight, does this lookup URL work for apps that have not been officially released yet?

<img width="811" alt="Bildschirmfoto 2021-08-03 um 13 56 47" src="https://user-images.githubusercontent.com/79841899/128011549-da29c8c9-c3a7-43c5-8708-45b83e4ff034.png">

**Comment by robingenz** [comment]
As far as I know, the app has to be officially released to get information via the iTunes Lookup API.
Unfortunately, I don't know any way to do this with Testflight.
I will close this issue for now.
Please test it again once the app is officially released.
If the problem still persists, please let me know so I can reopen the issue.

**Comment by sanderschnydrig** [comment]
@robingenz that is also the only information about it that I was able to gather. Will get back to you once I tested in production. Thanks a lot for the support and great work with this plugin!

**Comment by vycoder** [comment]
I just want to say, I encountered this same exact issue for the past 2 days. First time building my app on iOS, android is fine. Never bothered to look into the plugins I'm using until just now. Zero-ed in on this plugin and realized this isn't deployed yet.

Would be nice if we could include a note or something in the README regarding this error message.
