### ISSUE TITLE
bug: FlexibleUpdate never notifies the onFlexibleUpdateStateChange

### ISSUE THREAD

**Issue by saurioworker** [robingenz/capacitor-app-update#20]
**Describe the bug**
Hi, thanks for you plugin.
In Android using FlexibleUpdate option, it happens that the method **handleOnActivityResult**, deletes the Listener when handling the activity result, therefore the Listener never notifies the **onFlexibleUpdateStateChange**.

**To Reproduce**
Fragment implemented on javascript file:
```js
const appUpdateInfo = await AppUpdate.getAppUpdateInfo();
if (appUpdateInfo.updateAvailability === AppUpdateAvailability.UPDATE_AVAILABLE) {
   if (appUpdateInfo.flexibleUpdateAllowed) {     
      AppUpdate.addListener('onFlexibleUpdateStateChange', (state) => {
        console.log('Update State: ', state);
      });    
      let activityResult = await AppUpdate.startFlexibleUpdate()
   }
}
```

1. Go to `AppUpdate.java`, method `handleOnActivityResult`, after RESULT_OK, happen this:
2. Method `handleOnActivityResult`
3. After `resultCode == RESULT_OK`, begins to download
4. Error, deletes the listener while downloading occurs:
```java
if (requestCode == REQUEST_FLEXIBLE_UPDATE) {
   this.appUpdateManager.unregisterListener(this.listener);
   this.listener = null;
}
```

**Expected behavior**
It may be more convenient for the listener to be removed from the javascript file when a definitive status is reported.

**Smartphone information:**
- OS: [Android 7.0]
- Browser [Chrome]
- Version [92.0.4515.159]

**Comment by robingenz** [comment]
Hi @saurioworker,
thank you for your request.
Which plugin version are you using?

**Comment by saurioworker** [comment]
> Hi @saurioworker,
> thank you for your request.
> Which plugin version are you using?

Hi, the plugin version is: v1.0.0-alpha.2

**Comment by saurioworker** [comment]
Hi @robingenz ,
I see that the solution you present only applies when the "completeFlexibleUpdate" method is called, but 
in situations where the update is cancelled or fails, the listener will still be alive and listening.

**Comment by robingenz** [comment]
Thank you for pointing this out. I have updated this.
My fix is based on the latest version, which is v1.0.0-alpha.3.

I created another branch based on version `v1.0.0-alpha.2` and published it as dev version on npm:
```
npm i @robingenz/capacitor-app-update@1.0.0-dev.e353964.1629473800
```
Could you please test this version and let me know if it works now?
I'm also interested in feedback on the plugin in general, as I haven't had time to test the in-app update implementation myself.
Thank you!

**Comment by saurioworker** [comment]
Hi Robingenz, as you requested I have tested your fix and I am satisfied. Now the listener is released at the end of the process.
Overall the plugin meets the needs of my application. It has been easy to implement in my code, I have successfully tested the two update options (flexible and immediate), as well as to launch the update and send the app to the background and receive the notification of the completed download and execution of the "completeFlexibleUpdate" method.
I hope you can release a version for Capacitor 2 soon, as I can't update my project to Capacitor 3 at the moment.
Thanks for your dedication

**Comment by saurioworker** [comment]
Hi Robingenz, as you requested I have tested your fix and I am satisfied. Now the listener is released at the end of the process.
Overall the plugin meets the needs of my application. It has been easy to implement in my code, I have successfully tested the two update options (flexible and immediate), as well as to launch the update and send the app to the background and receive the notification of the completed download and execution of the "completeFlexibleUpdate" method.
I hope you can release a version for Capacitor 2 soon, as I can't update my project to Capacitor 3 at the moment.
Thanks for your dedication

**Comment by robingenz** [comment]
Thank you for your feedback! This is very helpful for me.
Unfortunately, I screwed up the semantic versioning a bit in this plugin. 😅 
For this reason I would like you to use the dev version until you have the possibility to update to Capacitor 3.
There should be no changes in the near future.
