### ISSUE TITLE
updates not available

### ISSUE THREAD

**Issue by migliori** [robingenz/capacitor-app-update#22]
Hi,

First thanks for your great & useful work.
I'm sure this is not a bug but more likely a noob question:

My app. is available on both the app store & play store.
I call AppUpdate.getAppUpdateInfo()

1. on IOS: the returned currentVersion is not the latest (1.2), but the previous one (1.1).
I opened https://itunes.apple.com/lookup?bundleId=xxx to check, and the latest 1.2 is in the result, so I don't understand why the plugin doesn't find it. Any idea?

2. on Android: I always get availableVersion: "0"
I test from Android Studio, but from the store it doesn't seem to find the latest version too.
I don't have any "$androidPlayCore version of com.google.android.play:core" in variables.gradle, but have no idea about what it means and how to implement it (sorry, I told you it was a noob question)

Thanks for your help

**Comment by sverdlov** [comment]
@migliori I had the same questions. But found [https://stackoverflow.com/questions/56118563/in-app-update-api-showing-update-not-available-while-testing-on-debugging-device](this) answer. Short, we need test it correctly.

**Comment by migliori** [comment]
My project is no more in development - it's live on both the [Play store](https://play.google.com/store/apps/details?id=org.ecoc2021.app) & [App store](https://apps.apple.com/us/app/ecoc-2021/id1577191230).

The App store returns the correct latest version (but 2 days after publishing ... not your fault of course)
But the Play Store always returns "0"

I send a notification to all users to remedy the problem.

**Comment by robingenz** [comment]
Please take a look at this [SO answer](https://stackoverflow.com/a/56383353/6731412).
> The most likely reason is that the Play Store on your device hasn't learnt about the new update yet.

Can you please try again? Maybe it was just a "cache problem" on Android as well.

Please make sure that it is a release build signed with the production key and follow [this guide](https://developer.android.com/guide/playcore/in-app-updates/test).

**Comment by mradosta** [comment]
Thanks for this plugin!

I have a similar issue:

I have the app installed from google play in my phone (tested inn 3 different android phones)

![WhatsApp Image 2021-10-06 at 8 01 17 AM](https://user-images.githubusercontent.com/33546/136191225-cfc105fc-83a0-4515-8e2b-ee5753c87a47.jpeg)


The app upgrade is ready and public available on play store:

![WhatsApp Image 2021-10-06 at 8 02 48 AM](https://user-images.githubusercontent.com/33546/136191321-16d8bc20-a2c1-4b1d-a7cb-a9ee9dc6b2fe.jpeg)
![WhatsApp Image 2021-10-06 at 8 03 19 AM](https://user-images.githubusercontent.com/33546/136191325-3aac770f-b05a-4cb9-9135-d06bb82b79a4.jpeg)

DATA
====
Current version installed on phone: 18
Available version in store: 20
Available version detected by plugin: 16 (prev version)

THE PROBLEM
===========
The plugin does not get notified about this new version. Phone restarted twice.

Any idea? Is there something I can do?
