### ISSUE TITLE
feat(ios): return `minOsVersion`

### ISSUE THREAD

**Issue by graemeenglish** [robingenz/capacitor-app-update#25]
I don't believe this library considers the minimum OS version for iOS when reporting updates available. Is that something that added?

**Comment by graemeenglish** [comment]
Yes I'm thinking of situation where the latest update of an app drops support for an older OS version so I probably do not want to advertise to a user that an update is available that they can't install. I'm guessing the android side handles this since it uses the sdk however iOS just uses the iTunes api so the library would need to check the current OS version and check against the minimum os version returned by the iTunes api.

**Comment by robingenz** [comment]
Oh, you're right. I did not think about that. I could additionally return the `minimumOsVersion`. The developer would then have to do the comparison himself.
Or do you have other suggestions for a solution?
You have to keep in mind that you manage the dialogs (etc.) yourself on iOS, unlike Android.

**Comment by graemeenglish** [comment]
You could do that yes however every user of the plugin would need to do the check. I'm thinking it is unlikely that devs will want to know the actual min os version so checking in the plugin would be a nice touch. Perhaps return both i.e. `minOsVersion` and `minOsVersionSupported`.

**Comment by robingenz** [comment]
The plugin could make this comparison but not the evaluation.
If the `minOsVersion` is higher than the current one, an update could still be available.

**Comment by graemeenglish** [comment]
Yes, so in that case as a plugin user I'd get to know an update is available through `updateAvailability` but since `minOsVersionSuported` is false I can tell the user to update their OS if possible or if not perhaps direct them to a PWA version of the app.

**Comment by robingenz** [comment]
Okay, now I understand what you mean by `minOsVersionSupported`. Good idea, I will keep that in mind.

**Comment by robingenz** [comment]
I have implemented this and created a PR. If you want, you can try it out: 
```
npm i npm i @robingenz/capacitor-app-update@1.2.0-dev.7d88d22.1639562398
```
