### ISSUE TITLE
Exposing client Staleness property in AppUpdateInfo

### ISSUE THREAD

**Issue by Rahul0106231** [robingenz/capacitor-app-update#27]
It would be nice if the plugin exposes the Client Staleness value so that the host app can decide to show felxible update / immediate update .

I know there is a priority for the same , but i feel this value can also be used in case the users are using an older version of the app.

**Comment by robingenz** [comment]
Hi @Rahul0106231,
thank your for your request!
I assume you mean [`clientVersionStalenessDays`](https://developer.android.com/reference/com/google/android/play/core/appupdate/AppUpdateInfo#clientVersionStalenessDays()).
Great idea!
