### ISSUE TITLE
Exposing AppUpdateInfo.installStatus() method

### ISSUE THREAD

**Issue by Saurabh120597** [robingenz/capacitor-app-update#28]
Greetings, a request to expose installStatus() method in AppUdateInfo as it let us know whether a flexible update has install pending. It is really important to handle the negative cases of a flexible update. Please look into it

below is the pseudo code from official docs:

 // If the update is downloaded but not installed,
 // notify the user to complete the update.
  if (appUpdateInfo.installStatus() == InstallStatus.DOWNLOADED) {
        popupSnackbarForCompleteUpdate();
   }

**Comment by robingenz** [comment]
Hi @Saurabh120597,
thank you for your request!
Good idea, that would be a useful addition.
So far this is only possible via [`addListener('onFlexibleUpdateStateChange', ...)`](https://github.com/robingenz/capacitor-app-update#addlisteneronflexibleupdatestatechange-).
