### ISSUE TITLE
Android - cannot return correct available version 

### ISSUE THREAD

**Issue by mrobst** [robingenz/capacitor-app-update#32]
Hi,  thanks for your great work with this plugin. 

I'm using version 1.3.0 with capacitor 3.3.3 for 2 android apps. In both cases the available version of my app returned by this code:

```
AppUpdate.getAppUpdateInfo().then(appUpdateInfo => {
      this.appUpdateInfo = appUpdateInfo;
      console.warn('app update info is ', this.appUpdateInfo)
    })
```

 is not the latest version but an older version. The only thing noticeable about the version that is returned is that it was running Android SDK 29, all versions after this were changed to use Android SDK 30. 

I can't see any way to find the logic that is used to get the available version (I assume this is in com.google.android.play:core which I'm using the latest version of 1.10.2). I've tried clearing the Google Play cache on the phone, checking the countries the app is available for, making sure there are no previous versions active in other tracks etc). 

My apps are running on Google Play (one in open testing and one in production) and I can update them via Google Play when I push app updates (i.e. the play store recognises that updates are available and allows me to manually install them). I cannot figure out why the plugin does not see the latest version but only a specific older one?!

Example app: app.scafol.io.staging

Shown on the phone using this plugin:
![WIN_20211221_09_30_21_Pro](https://user-images.githubusercontent.com/20040193/146906234-3b736d54-8d7d-44ae-a72a-19a616cb9ae7.jpg)

Versions available in Google Play:
![image](https://user-images.githubusercontent.com/20040193/146903541-81e54275-fc2e-4156-9289-48960897ca03.png)

Any pointers for resolving this would be greatly appreciated!
thanks
Marcus

**Comment by robingenz** [comment]
Hi @mrobst,
thank you for your interest in this plugin and your detailed request.
I'll try to help you as much as I can.
Unfortunately, I don't have much control over this output, as this output comes from the Play Core library.

> In both cases the available version of my app returned by this code: ... is not the latest version but an older version.

In my personal experience, there can be two reasons for this behavior:
1. The Play Store on your device hasn't learnt about the new update yet (see https://stackoverflow.com/a/56383353).
2. The device does not support the app version and cannot receive the update.

However, according to your description, neither seems to apply. That is very strange.
I will research what else it could be and let you know.

Does this problem occur only on a few devices and on all devices?

> I can't see any way to find the logic that is used to get the available version

See https://github.com/robingenz/capacitor-app-update/blob/38a1e5ad6cef80f96ef19241856ac46498adfe5e/android/src/main/java/dev/robingenz/capacitor/appupdate/AppUpdatePlugin.java#L58 and https://github.com/robingenz/capacitor-app-update/blob/38a1e5ad6cef80f96ef19241856ac46498adfe5e/android/src/main/java/dev/robingenz/capacitor/appupdate/AppUpdatePlugin.java#L71

**Comment by mrobst** [comment]
Hi thanks for the quick reply. I've installed the app on 3 different phones now and I get different values for availableVersion on each one!? One says version 0, one says 10713 and one says 10613. Its very strange :-(

Do you know if there is a way I can raise this as a bug/issue with the Play Core Library team?

thanks
Marcus

**Comment by robingenz** [comment]
As I said, that different devices show different versions is normal, because it may be that on some devices the Play Store background job to update has not yet run through. But after a few days the versions should be in sync (assuming all devices support the update etc.).
Also, to be on the safe side, check out this comment to make sure you're testing it correctly: https://github.com/robingenz/capacitor-app-update/issues/18#issuecomment-886706841

> Do you know if there is a way I can raise this as a bug/issue with the Play Core Library team?

To be honest, I'm not 100% sure.
I would use the [Google issuetracker](https://issuetracker.google.com/issues/new?component=190923&template=841312).

If you report an issue there, you are very welcome to post the link here so we can track it.

**Comment by robingenz** [comment]
Hi @mrobst,
Do you have any news? Were you able to solve the problem?

**Comment by mrobst** [comment]
Hi - apologies for the lack of feedback from me. The plugin is functionally working, I've been able to check on a couple of phones and it seems that after some time the available update is recognised and I can trigger the in-app update. I have never been able to return a release date for the (new) available version (shown blank in the screenshot above) but this doesn't impact the ability to upgrade. 
After the plugin is used to trigger an app update it correctly shows the current version and then the version of future releases. It seems on first install / use an old version is reported as the current version, I never solved why that was :-(

I'll close the issue now as far as I can tell there is nothing for you to change about this plugin, thanks!

**Comment by robingenz** [comment]
@mrobst Thank you for your feedback! This will help me with similar questions in the future.
