### ISSUE TITLE
feat: Capacitor 2 support

### ISSUE THREAD

**Issue by sfrinx** [robingenz/capacitor-app-update#33]
Hi,
thank you for this plugin support.

In my project i use capacitor 2, and at the moment i can't update to capacitor 3.
I try to use this versione of your plugin: "https://github.com/robingenz/capacitor-app-update/tree/robingenz/capacitor-2" but when i try to import "import dev.robingenz.capacitor.appupdate.AppUpdate;" in mainActivity, android studio not found dependency.

This version is valid?
Thank you

**Comment by robingenz** [comment]
Hi @sfrinx,
thank you for your request.
Yes, this version should still work for Capacitor v2.
Please make sure you run: `npx cap sync`.
If this does not help, please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)).

Just out of interest: For what reason can't you update to Capacitor 3? Maybe I can help you or give you a tip.

**Comment by sfrinx** [comment]
Thank you for your quick response.
After a lot of search i found that the problem is android studio cache. After i invalidate it plugin works well.
Now i'm going to investigate on this IOS error: "Required app information could not be fetched".

About capacitor, i can't upgrade because i use some plugins that are not compatible with angular 9+ version (required for new capacitor dependencies) and i'm not sure that all work fine.

**Comment by robingenz** [comment]
Great that it works now!

> Edit: I found a similar issue "#19"

Let me know if this issue doesn't help you.

> About capacitor, i can't upgrade because i use some plugins that are not compatible with angular 9+ version (required for new capacitor dependencies) and i'm not sure that all work fine.

Okay, too bad. I can only recommend Capacitor 3. There have been great improvements. Maybe you can find a replacement for the plugins.
