### ISSUE TITLE
immediateUpdateAllowed Question

### ISSUE THREAD

**Issue by piyushnh** [robingenz/capacitor-app-update#37]
How is the immediateUpdateAllowed variable set? Do we have to set it? or is it set automatically?

**Comment by robingenz** [comment]
Hi @piyushnh,
Which variable do you mean exactly?

Here is an example of how you can perform an immediate update:

```ts
const performImmediateUpdate = async () => {
  const result = await AppUpdate.getAppUpdateInfo();
  if (result.updateAvailability !== AppUpdateAvailability.UPDATE_AVAILABLE) {
    return;
  }
  if (result.immediateUpdateAllowed) {
    await AppUpdate.performImmediateUpdate();
  }
};
```

**Comment by piyushnh** [comment]
I'm referring to the result.isImmediateUpdateAllowed one. Is that
automatically set by play core library?

**Comment by robingenz** [comment]
Yes, this value comes from the Play Core library.
You must call the `getAppUpdateInfo` method to get access to this value.
Does this answer your question?

**Comment by piyushnh** [comment]
Yes it does, thank you!
