### ISSUE TITLE
feat: Does it support updating applications from custom source addresses

### ISSUE THREAD

**Issue by estoi** [robingenz/capacitor-app-update#38]
**Is your feature request related to a problem? Please describe.**
Google play is not required to update the application from a custom source address.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by robingenz** [comment]
Hi @estoi,
thank you for your request.
I'm not sure I understood you correctly. If the request is if you can do live updates with this plugin like you can with Ionic Appflow, then the answer is no.
This plugin only works with the Google Play Store on Android.
For this reason, I am closing this issue. Let me know if you meant something else.

**Comment by estoi** [comment]
> 

I am looking for other solutions.
