### ISSUE TITLE
feat: App Gallery Support

### ISSUE THREAD

**Issue by jongbonga** [robingenz/capacitor-app-update#39]
**Is your feature request related to a problem? Please describe.**
The plugin currently works with App Store & Google Play but not App Gallery (Huawei)

**Describe the solution you'd like**
Can the plugin support when opening the Store?

**Describe alternatives you've considered**
An alternative that I'm considering would be to use `App.canOpenUrl({ url: "com.huawei.appmarket" })` to detect if the device falls within App Gallery range and open the store somehow

**Comment by robingenz** [comment]
Hi @jongbonga,
As far as I know, in-app updates for Android are not supported by the App Gallery.
For this reason, I am closing this issue.

> An alternative that I'm considering would be to use App.canOpenUrl({ url: "com.huawei.appmarket" }) to detect if the device falls within App Gallery range and open the store somehow

I think you should be able to open the App Gallery using https://github.com/robingenz/capacitor-app-update#openappstore. Give it a try.
