### ISSUE TITLE
[Question] Does this only look at prod listings

### ISSUE THREAD

**Issue by 0xRenshaw** [robingenz/capacitor-app-update#44]
Hello, 

I've tried to locate this information within the documents available and within the issues and been unsuccessful. 

I think I already know the answer, but I'd like confirmation to ensure It is what I think and not a bug/misconfig.

Question, does this only support/look at production store listing on Android/iOS. I have an app which is still in development and therefore isn't yet available in prod - only TestFlight & Open Beta tracks. 

When running locally, I encounter the following console error message
``Required app information could not be fetched``

Tom

**Comment by robingenz** [comment]
Hi @0xRenshaw,
Yes, as far as I know, there must be at least one prod version.
If the prod version is available, you can test with internal app sharing: https://developer.android.com/guide/playcore/in-app-updates/test
Best release the first app version without this plugin and add it afterwards.
