### ISSUE TITLE
hello 👋

### ISSUE THREAD

**Issue by stewones** [robingenz/capacitor-app-update#45]
just to say thanks, your plugin is awesome 👏, just implemented it without any headache.

I see you follow lots of @capacitor-community best practices and was just wondering why not move your repo over there? you could reach a higher audience and more peeps from community helping you with maintenance, new features, etc. just an idea, if you want I can assist you over migration.

Thank you again

**Comment by robingenz** [comment]
Hi @stewones 👋
thank you very much, glad everything worked out!
I already maintain a few Capacitor community plugins, but appreciate the freedom of owning the repository yourself (you have access to all repository settings, etc).
For that reason, I don't plan to move the plugin to the Capacitor Community Org for the time being.
